
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="assets/css/legalNotice.css">
</head>
<body>

    <?php require 'assets/partials/header.php' ?>

    <div class="containerLegal">
        <svg xmlns="http://www.w3.org/2000/svg" width="1502" height="1635" viewBox="0 0 1502 1635">
            <g id="Groupe_1" data-name="Groupe 1" transform="translate(-209 -350)">
                <text id="mentions_légales" data-name="mentions légales" transform="translate(426 447)" fill="#121619" font-size="100" font-family="Montserrat-Bold, Montserrat" font-weight="700"><tspan x="0" y="0">MENTIONS LÉGALES</tspan></text>
                <text id="mentions_légales_du_site_mangwa.com" data-name="mentions légales du site mangwa.com" transform="translate(562 482)" fill="#121619" font-size="40" font-family="Montserrat-SemiBold, Montserrat" font-weight="600"><tspan x="0" y="0">mentions légales du site mangwa.com</tspan></text>
                <text id="Le_présent_site_ci-après_le_Site_est_la_propriété_de_la_société_Mangwa:" data-name="Le présent site (ci-après « le Site ») est la propriété de la société Mangwa:" transform="translate(209 719)" fill="#121619" font-size="20" font-family="Rubik-Medium, Rubik" font-weight="500"><tspan x="0" y="0">Le présent site (ci-après « le Site ») est la propriété de la société Mangwa:</tspan></text>
                <text id="Mangwa_SA_au_capital_de_5_000_000_Siret_RCS_de_Grenoble_:_302_069_414_00027_N_TVA_Intracommunautaire_:_FR_13_302_069_414_Siège_social_:_37_Rue_Servan_-_BP_177_-_38008_GRENOBLE_CEDEX_1_Tél_:_33_0_4_76_88_75_75" data-name="Mangwa
        SA au capital de 5 000 000 €
        Siret (RCS de Grenoble) : 302 069 414 00027
        N° TVA Intracommunautaire : FR 13 302 069 414
        Siège social : 37, Rue Servan - BP 177 - 38008 GRENOBLE CEDEX 1
        Tél : +33 (0)4 76 88 75 75" transform="translate(209 776)" fill="#121619" font-size="20" font-family="Rubik-Medium, Rubik" font-weight="500"><tspan x="0" y="0">Mangwa</tspan><tspan x="0" y="24">SA au capital de 5 000 000 €</tspan><tspan x="0" y="48">Siret (RCS de Grenoble) : 302 069 414 00027</tspan><tspan x="0" y="72">N° TVA Intracommunautaire : FR 13 302 069 414</tspan><tspan x="0" y="96">Siège social : 37, Rue Servan - BP 177 - 38008 GRENOBLE CEDEX 1</tspan><tspan x="0" y="120">Tél : +33 (0)4 76 88 75 75</tspan></text>
                <text id="Nom_du_directeur_de_la_publication_:_Tristan_Gauthier" data-name="Nom du directeur de la publication : Tristan Gauthier" transform="translate(209 967)" fill="#121619" font-size="20" font-family="Montserrat-SemiBold, Montserrat" font-weight="600"><tspan x="0" y="0" text-decoration="underline">Nom du directeur de la publication </tspan><tspan y="0" font-family="SegoeUI, Segoe UI" font-weight="400">: Tristan Gauthier</tspan></text>
                <text id="Propriété_Intellectuelle_Le_Site_est_une_œuvre_protégée._L_intégralité_des_contenus_marques_slogans_graphismes_photographies_animations_vidéos_bases_de_données_et_textes_quels_que_soient_leurs_formats_et_plus_généralement_tous_les_éléments_compos" data-name="Propriété Intellectuelle

        Le Site est une œuvre protégée. L&apos;intégralité des contenus, marques, slogans, graphismes, photographies, animations, vidéos, bases de données et textes, quels que soient leurs formats, et plus généralement tous les éléments compos" transform="translate(209 1028)" fill="#121619" font-size="20" font-family="Montserrat-SemiBold, Montserrat" font-weight="600"><tspan text-decoration="underline"><tspan x="0" y="19">Propriété Intellectuelle</tspan></tspan><tspan font-family="SegoeUI, Segoe UI" font-weight="400"><tspan x="0" y="46"></tspan></tspan><tspan font-family="Rubik-Light, Rubik" font-weight="300"><tspan x="0" y="70">Le Site est une œuvre protégée. L&apos;intégralité des contenus, marques, slogans, graphismes, photographies, animations, vidéos, bases de </tspan><tspan x="0" y="94">données et textes, quels que soient leurs formats, et plus généralement tous les éléments composant le Site sont la propriété exclusive </tspan><tspan x="0" y="118">de MANGWA Ils ne peuvent être reproduits, utilisés ou représentés sous peine de poursuites judiciaires.</tspan><tspan x="0" y="142"></tspan><tspan x="0" y="166">Il en est de même des développements informatiques, technologies et développements sous-jacents constituant le Site. Ils ne peuvent </tspan><tspan x="0" y="190" xml:space="preserve">donc être reproduits, décompilés, désassemblés sans autorisation expresse préalable de Mangwa  sous peine de poursuites judicaires</tspan><tspan x="0" y="214"></tspan><tspan x="0" y="238">Toute reproduction totale ou partielle des contenus du Site, par quelque procédé que ce soit, est interdite et constitue une contrefaçon </tspan><tspan x="0" y="262">sanctionnée par les articles L.335-2 et suivants et les articles L.713-1 et suivants du Code de la Propriété intellectuelle.</tspan><tspan x="0" y="286" xml:space="preserve"> L’Utilisateur s’engage à n’utiliser aucun contenu du Site hors le cadre des présentes, sauf autorisation expresse du responsable de la </tspan><tspan x="0" y="310">publication. Les contenus du Site ne peuvent faire l&apos;objet de copie qu&apos;à titre d&apos;information, la copie étant réservée au seul usage privé.</tspan></tspan></text>
                <text id="Garanties_-_Responsabilité_Limitée_L_utilisateur_utilise_les_services_du_Site_à_ses_risques_et_périls._MANGWA_ne_peut_garantir_en_aucun_cas_que_les_services_proposés_ne_subiront_aucune_interruption_l_obligation_de_fourniture_de_contenus_d_information_se" data-name="Garanties - Responsabilité Limitée

        L’utilisateur utilise les services du Site à ses risques et périls. MANGWA  ne peut garantir en aucun cas que les services proposés ne subiront aucune interruption, l&apos;obligation de fourniture de contenus d’information se" transform="translate(209 1476)" fill="#121619" font-size="20" font-family="Montserrat-SemiBold, Montserrat" font-weight="600"><tspan text-decoration="underline"><tspan x="0" y="19">Garanties - Responsabilité Limitée</tspan></tspan><tspan font-family="Rubik-Light, Rubik" font-weight="300"><tspan x="0" y="43"></tspan><tspan x="0" y="67" xml:space="preserve">L’utilisateur utilise les services du Site à ses risques et périls. MANGWA  ne peut garantir en aucun cas que les services proposés ne subiront aucune interruption, </tspan><tspan x="0" y="91">l&apos;obligation de fourniture de contenus d’information se limitant à une obligation de moyen.</tspan><tspan x="0" y="115"></tspan><tspan x="0" y="139">Les articles proposés sont conformes à la législation française en vigueur. MANGWA assure seule la responsabilité des informations fournies. MANGWA s&apos;efforce </tspan><tspan x="0" y="163">d&apos;assurer au mieux de ses possibilités, l&apos;exactitude et la mise à jour des informations diffusées sur le Site, dont il se réserve le droit de corriger, à tout moment et sans </tspan><tspan x="0" y="187" xml:space="preserve">préavis, le contenu. Les informations contenues sur le Site peut donc présenter des erreurs techniques et typographiques ou autres inexactitudes. MANGWA  ne </tspan><tspan x="0" y="211">garantit pas que les fonctions contenues dans ces documents seront assurées sans interruption et sans erreur, ni que le Site ou le serveur qui les met à disposition </tspan><tspan x="0" y="235">soit exempts de virus et autres composants dangereux. MANGWA prend toutes les précautions pour que le contenu du Site ne soit pas contraire à l&apos;ordre public et aux </tspan><tspan x="0" y="259">bonnes mœurs. Toutefois, si des idées ou images heurtaient certaines personnes particulièrement sensibles, MANGWA ne saurait en être responsable.</tspan><tspan x="0" y="283"></tspan><tspan x="0" y="307">En conséquence, MANGWA décline toute responsabilité : pour toute imprécision, inexactitude ou omission portant sur des informations disponibles sur le Site ; pour </tspan><tspan x="0" y="331">tous dommages résultant d&apos;une intrusion frauduleuse d&apos;un tiers ayant entraîné une modification des informations mises à la disposition sur le Site ; et plus </tspan><tspan x="0" y="355">généralement pour tous dommages, directs ou indirects, qu&apos;elles qu&apos;en soient les causes, origines, nature ou conséquences, provoqués à raison de l&apos;accès de </tspan><tspan x="0" y="379">quiconque au Site ou de l&apos;impossibilité d&apos;y accéder, de même que l&apos;utilisation du Site et/ou du crédit accordé à une quelconque information provenant directement ou </tspan><tspan x="0" y="403">indirectement de ce dernier.</tspan></tspan></text>
            </g>
        </svg>
    </div>

    <?php require 'assets/partials/footer.php' ?>

</body>
</html>